### ISSUE TITLE
Data scraping function

### ISSUE THREAD

**Issue by BraulioPerez** [BraulioPerez/ws_MercadoLibre#2]
Develop a funcion in python that extracts all the data from an item, It should take the item url as an input and return a list with the data in order [Title, vendor, Original price, current price, description, rating, number of ratings]

**Comment by Frank3040** [comment]
I already uploaded the script which contains the first version of the function. It still needs to be improved by adding some validations.

**Comment by BraulioPerez** [comment]
Falta adaptar la funcion para que funcione con la logica base del scraper para poder implementarlo de forma asincrona y multiprocesada

**Comment by BraulioPerez** [comment]
Closed the issue due to project changing
