### ISSUE TITLE
Create the template for the database in mysql 

### ISSUE THREAD

**Issue by BraulioPerez** [BraulioPerez/ws_MercadoLibre#4]
Carlos should create a mysql server and add a table with the columns title, vendor, vendor url, og price, current price, description, rating, # ratings

**Comment by DeathSpain7** [comment]
![Captura de pantalla 2024-01-26 143529](https://github.com/BraulioPerez/ws_MercadoLibre/assets/144395489/1a8d1f65-e165-47e8-96e3-0e84c19f4496)

**Comment by BraulioPerez** [comment]
Great Job, once finished, we can begin extracting info, thx for completing on time!
